import {APP_VERSION,INGREDIENTS,SPECIES,BASE_INGREDIENTS,GLUCOSE_INGREDIENTS,calculate,scaleRows,spoonMeasure,validateRecipe,validatePack,validVolume,format,compareVersions,withBase,withGlucose,withLoSalt,defaultBaseChoice,encodeShareState,decodeShareState} from './model.js?v=1.3.0';
const $=id=>document.getElementById(id), text=(id,value)=>$(id).textContent=value;
const PACK_KEY='ors-pack-v3', LOCAL_KEY='ors-local-v1', INSTALL_KEY='ors-install-dismissed-v1';
let saltChoice='kcl',baseChoice=null,glucoseChoice=null;
let pack,local=[],sharedRecipe=null,recipe,volume=1000,mode='weight',pendingPack,registration,installPrompt,draft,editingId=null,networkState='Loading',canStore=true,booted=false;
const read=(key)=>{try{return JSON.parse(localStorage.getItem(key));}catch{return null;}};
const save=(key,value)=>{try{localStorage.setItem(key,JSON.stringify(value));return true;}catch{canStore=false;text('storage-status','Local storage unavailable. Custom recipes and preferences cannot be saved.');return false;}};
const node=(tag,content,cls)=>{const n=document.createElement(tag);if(content!==undefined)n.textContent=content;if(cls)n.className=cls;return n;};
const allRecipes=()=>[...pack.recipes,...local,...(sharedRecipe?[sharedRecipe]:[])];
function getCachedPack(){try{return validatePack(read(PACK_KEY));}catch{return null;}}
function updateStatus(){text('connection',navigator.onLine?networkState:'Offline · saved recipes');}
async function fetchPack(){
 const response=await fetch('./data/recipes-v2.json',{cache:'no-store',signal:AbortSignal.timeout(2500)});
 if(!response.ok)throw Error('Recipe server unavailable');
 const data=validatePack(await response.json());
 if(response.headers.get('X-ORS-Cache')==='fallback')throw Object.assign(Error('Using saved copy'),{fallback:data});
 return data;
}
function populateRecipes(selected,reset=true){
 $('recipe').replaceChildren();const grouped=new Map();
 for(const r of pack.recipes){const label=r.group||'Source formulae';if(!grouped.has(label))grouped.set(label,[]);grouped.get(label).push(r);}
 for(const [label,recipes]of grouped){const group=node('optgroup');group.label=label;for(const r of recipes){const option=node('option',r.name);option.value=r.id;group.append(option);} $('recipe').append(group);}
 if(local.length){const group=node('optgroup');group.label='Custom recipes · this device';for(const r of local){const option=node('option',r.name);option.value=r.id;group.append(option);}$('recipe').append(group);}
 if(sharedRecipe){const group=node('optgroup');group.label='Shared recipe';const option=node('option',sharedRecipe.name);option.value=sharedRecipe.id;group.append(option);$('recipe').append(group);}
 recipe=allRecipes().find(r=>r.id===selected)||pack.recipes[0];$('recipe').value=recipe.id;if(reset)resetSubstitutions();render();
}
function resetSubstitutions(){saltChoice='kcl';baseChoice=defaultBaseChoice(recipe);glucoseChoice=recipe.ingredients.find(r=>GLUCOSE_INGREDIENTS.includes(r.id))?.id||null;}
function activeRecipe(){let active=recipe;if(baseChoice&&recipe.baseOptions)active=withBase(active,baseChoice);if(glucoseChoice&&recipe.ingredients.some(r=>GLUCOSE_INGREDIENTS.includes(r.id)))active=withGlucose(active,glucoseChoice);if(saltChoice==='losalt')active=withLoSalt(active);return active;}
function saltAvailableFor(r){return r.ingredients.some(x=>x.id==='kcl')&&r.ingredients.some(x=>x.id==='nacl')&&!r.ingredients.some(x=>['losalt','losaltLabel'].includes(x.id));}
function shareableCustom(r){const keys=['id','name','version','description','ingredients','spoons','method','storage','basis','warning','sources','compositionMode','volumeBasis','published','carbohydrateGL','category','carbohydrateForm','osmotic'];const out={};for(const key of keys)if(r[key]!==undefined)out[key]=structuredClone(r[key]);out.id='shared-recipe';out.name=r.name.replace(/ - custom recipe$/i,'')+' · shared';out.version=String(r.version||'1');out.sources=out.sources||[];return validateRecipe(out);}
function currentShareState(){return recipe.local||recipe.shared?{custom:shareableCustom(activeRecipe()),v:volume,m:mode,b:null,g:null,s:'kcl',pv:pack.version}:{r:recipe.id,v:volume,m:mode,b:baseChoice,g:glucoseChoice,s:saltChoice,pv:pack.version};}
function syncUrl(){if(!booted||!recipe)return;const url=new URL(location.href);url.hash=`s=${encodeShareState(currentShareState())}`;history.replaceState(null,'',url);}
function readSharedState(){try{const params=new URLSearchParams(location.hash.slice(1)),token=params.get('s');return token?decodeShareState(token):null;}catch{return null;}}
function applySharedState(state){
 if(!state)return false;
 if(state.custom){sharedRecipe={...structuredClone(state.custom),id:'shared-recipe',shared:true,local:false};recipe=sharedRecipe;}else{recipe=pack.recipes.find(r=>r.id===state.r);if(!recipe)return false;}
 volume=state.v;mode=state.m;baseChoice=recipe.baseOptions?.[state.b]?state.b:defaultBaseChoice(recipe);glucoseChoice=recipe.ingredients.some(r=>GLUCOSE_INGREDIENTS.includes(r.id))&&GLUCOSE_INGREDIENTS.includes(state.g)?state.g:recipe.ingredients.find(r=>GLUCOSE_INGREDIENTS.includes(r.id))?.id||null;saltChoice=state.s==='losalt'&&saltAvailableFor(recipe)?'losalt':'kcl';
 populateRecipes(recipe.id,false);return true;
}
function amountText(amount,def){if(def.unit==='tablets')return `${format(amount,3)} tablet${amount===1?'':'s'}`;return `${format(amount,3)} ${def.unit}`;}
function renderProfile(values){$('profile').replaceChildren();const items=[recipe.category||'Custom recipe'];if(values.potassium!==undefined)items.push(values.potassium?`K ${format(values.potassium,0)} mmol/L`:'Potassium-free');if(recipe.carbohydrateForm)items.push(recipe.carbohydrateForm);for(const value of items)$('profile').append(node('span',value));}
function renderPrint(active,values,rows,osm){
 text('print-title',recipe.name);text('print-volume',`${format(volume)} mL · ${recipe.volumeBasis==='ready'?'ready to use':recipe.volumeBasis==='final'||recipe.local?'final volume':'water added'}`);text('print-version',`Recipe ${recipe.version} · pack ${pack.version}`);
 $('print-ingredients').replaceChildren();for(const row of rows){const tr=node('tr');tr.append(node('th',INGREDIENTS[row.id].name),node('td',amountText(row.amount,INGREDIENTS[row.id])));$('print-ingredients').append(tr);}
 text('print-water',recipe.volumeBasis==='ready'?'No water to add.':`${recipe.volumeBasis==='final'||recipe.local?'Make up with water to':'Water to add'}: ${format(volume)} mL`);
 $('print-composition').replaceChildren();const printable=['sodium','potassium','chloride','glucose','citrate','bicarbonate','calcium','magnesium','lactate'];for(const key of printable){if(values[key]===undefined||(!values[key]&&!['potassium','bicarbonate'].includes(key)))continue;const box=node('div');box.append(node('span',key[0].toUpperCase()+key.slice(1)),node('strong',`${format(values[key],0)} mmol/L`));$('print-composition').append(box);}if(osm){const box=node('div');box.append(node('span',osm.kind),node('strong',`${format(osm.value,0)} ${osm.unit}`));$('print-composition').append(box);}
 text('print-method',recipe.method||'Calculation only.');text('print-storage',recipe.storage||'');text('print-source',recipe.sources.map(s=>s.title).join(' · '));text('print-generated',`Generated by ORS Recipes ${APP_VERSION} · ${new Date().toLocaleDateString('en-GB')}`);
}
function render(){
 const active=activeRecipe(),ready=recipe.volumeBasis==='ready',published=recipe.compositionMode==='published'?recipe.published:null;
 const baseAvailable=!!recipe.baseOptions&&recipe.ingredients.some(r=>BASE_INGREDIENTS.includes(r.id));
 const glucoseAvailable=recipe.ingredients.some(r=>GLUCOSE_INGREDIENTS.includes(r.id));
 const saltAvailable=saltAvailableFor(recipe);
 $('base-option').hidden=!baseAvailable;$('glucose-option').hidden=!glucoseAvailable;$('salt-option').hidden=!saltAvailable;$('substitutions').hidden=!baseAvailable&&!glucoseAvailable&&!saltAvailable;
 if(baseAvailable){$('base-choice').replaceChildren();for(const [key,option]of Object.entries(recipe.baseOptions)){const item=node('option',option.label);item.value=key;$('base-choice').append(item);}const unavailable=node('option','Sodium carbonate · no sourced substitution');unavailable.disabled=true;$('base-choice').append(unavailable);$('base-choice').value=baseChoice;}
 if(glucoseAvailable)$('glucose-choice').value=glucoseChoice;if(saltAvailable)$('salt-choice').value=saltChoice;
 text('salt-note',saltChoice==='losalt'?'LoSalt Original label values: sodium 133 mg/g and potassium 346 mg/g. The separate table-salt mass is reduced automatically.':'LoSalt is available where the formula contains both table salt and potassium chloride.');
 $('weight').closest('.segmented').hidden=ready;text('start-editor',recipe.local?'Edit custom recipe':'Create custom recipe');$('start-editor').hidden=['pedialyte','clinova-16'].includes(recipe.id)||recipe.shared;
 let description=recipe.description||'Local formulation';if(baseAvailable)description+=` · ${recipe.baseOptions[baseChoice].label}`;if(glucoseAvailable&&glucoseChoice!==recipe.ingredients.find(r=>GLUCOSE_INGREDIENTS.includes(r.id))?.id)description+=` · ${INGREDIENTS[glucoseChoice].name}`;text('description',description);
 text('volume-basis',ready?'Ready-to-use volume':recipe.volumeBasis==='final'||recipe.local?'Final solution':'Water added');text('water-label',ready?'Water to add':recipe.volumeBasis==='final'||recipe.local?'Make up with water to':'Water to add');text('water',ready?'None':`${format(volume)} mL`);
 $('volume').value=volume;$('slider').value=Math.round(volume/50)*50;$('minus').disabled=volume<=50;$('plus').disabled=volume>=5000;document.querySelectorAll('[data-volume]').forEach(b=>b.setAttribute('aria-pressed',Number(b.dataset.volume)===volume));$('weight').setAttribute('aria-pressed',mode==='weight');$('spoons').setAttribute('aria-pressed',mode==='spoons');
 text('measurement-note',ready?'Ready-to-use product; no dilution.':mode==='spoons'?'Spoon volumes are approximate; use scales for rows without a source spoon measure.':'Weights are scaled directly from the selected formula and chemical forms.');
 $('ingredients').replaceChildren();const rows=scaleRows(active,volume);
 for(const row of rows){const def=INGREDIENTS[row.id],item=node('div',undefined,'ingredient'),left=node('div');left.append(node('div',def.name,'ingredient-name'));if(['productGlucose','productCitrate'].includes(row.id))left.append(node('div','Product-specification ingredient','ingredient-sub'));const right=node('div',undefined,'ingredient-amount'),spoon=mode==='spoons'?spoonMeasure(active,row,volume):null;if(spoon){right.append(node('span',`≈ ${format(spoon.count)} × ${format(spoon.size)} mL`),node('small',`${spoon.heaped?'heaped':'level'} spoon${spoon.count===1?'':'s'} · ${format(row.amount,3)} g`));}else{right.append(node('span',amountText(row.amount,def)));if(mode==='spoons'&&def.unit==='g')right.append(node('small','Use scales'));if(def.unit==='drops'&&!Number.isInteger(row.amount))right.append(node('small','Fractional drops cannot be measured reliably'));}item.append(left,right);$('ingredients').append(item);}
 text('precision-note',ready?'Pour the required volume without adding water.':rows.some(r=>r.amount>0&&r.amount<.05)?'This batch includes a mass below 50 mg; use a suitable milligram scale.':rows.some(r=>r.amount>0&&r.amount<1)?'This batch includes sub-gram quantities; use suitable scales.':'Use a calibrated scale for reproducible weights.');
 const calc=calculate(active),values=published||calc.values,useLoSalt=saltChoice==='losalt';renderProfile(values);
 text('composition-kind',published?(useLoSalt?'Published target · LoSalt-adjusted ingredients':'Published product reference'):calc.unknown.length?'Known-ingredient subtotal':'Calculated from shown ingredients');
 const names={sodium:'Sodium · Na⁺',potassium:'Potassium · K⁺',chloride:'Chloride · Cl⁻',glucose:'Glucose',sucrose:'Sucrose',citrate:'Citrate',bicarbonate:'Bicarbonate',carbonate:'Carbonate',calcium:'Calcium · Ca²⁺',magnesium:'Magnesium · Mg²⁺',lactate:'Lactate',zinc:'Zinc · Zn²⁺'},optional=['sucrose','carbonate','calcium','magnesium','lactate','zinc'];
 $('concentrations').replaceChildren();for(const key of SPECIES){if(optional.includes(key)&&(!published&&!values[key]||published&&values[key]===undefined))continue;const row=node('div'),known=values[key]!==undefined,dd=node('dd',known?format(values[key],0):'—');if(known){dd.title=`${format(values[key],4)} mmol/L before rounding`;dd.setAttribute('aria-label',`${format(values[key],4)} mmol per litre; displayed rounded`);}else dd.title='Not established for this product';row.append(node('dt',names[key]),dd);$('concentrations').append(row);}
 let osm=recipe.osmotic;if(recipe.osmoticAppliesToBase&&baseChoice!==recipe.osmoticAppliesToBase)osm=null;if(useLoSalt)osm=null;if(!osm&&!published&&calc.osmolarity!==null)osm={value:calc.osmolarity,unit:'mOsm/L',kind:'Calculated ideal osmolarity'};text('osm-label',osm?.kind||'Osmotic value');text('osmolarity',osm?`${osm.kind.startsWith('Calculated')?'≈ ':''}${format(osm.value,0)}`:'Not verified');text('osm-unit',osm?.unit||'No sourced value');
 text('ratio',values.sodium&&values.glucose?`${format(values.sodium/values.glucose,2)}:1`:'—');
 $('unknowns').hidden=!!published||!calc.unknown.length;text('unknowns',`Unmodelled contributions: ${calc.unknown.join(', ')}. Displayed electrolyte amounts may underestimate the totals.`);
 text('carbohydrate',recipe.carbohydrateGL===undefined?'':`${recipe.carbohydrateForm||'Carbohydrate'}: ${format(recipe.carbohydrateGL,1)} g/L · ${format(recipe.carbohydrateGL*volume/1000,1)} g in this batch.`);$('carbohydrate').hidden=recipe.carbohydrateGL===undefined;
 text('basis',(recipe.basis||'Nominal calculation from the entered grams per litre and selected chemical forms.')+(active.variantNotes?.length?' '+active.variantNotes.join(' '):'')+' Unrounded composition (mmol/L): '+Object.entries(values).filter(([key])=>SPECIES.includes(key)).map(([key,value])=>key+' '+format(value,4)).join('; ')+'.');
 text('totals',`${published?'Reference':'Calculated'} amount in this batch: sodium ${format((values.sodium||0)*volume/1000,1)} mmol; potassium ${format((values.potassium||0)*volume/1000,1)} mmol.`);text('method',recipe.method||'Calculation only.');text('storage',recipe.storage||'Storage stability has not been established.');text('recipe-warning',(useLoSalt?'LoSalt uses rounded label values and unmodelled minor ingredients. ':'')+(recipe.warning||'This custom calculation has no independent formulation review.')+(baseAvailable?' Sodium carbonate is chemically distinct and has no sourced automatic substitution here.':''));
 let unitNote='';if(recipe.waterPerSachet){const count=volume/recipe.waterPerSachet;unitNote=Number.isInteger(count)?`${count} whole sachet${count===1?'':'s'} for ${format(volume)} mL water.`:`${format(count)} sachets would be required. Choose a whole-sachet volume (${recipe.waterPerSachet} mL steps).`;}else if(recipe.wholeUnit){const count=volume/recipe.wholeUnit.volumePerUnit;unitNote=Number.isInteger(count)?`${count} whole ${count===1?recipe.wholeUnit.singular:recipe.wholeUnit.plural} for ${format(volume)} mL water.`:`${format(count)} ${recipe.wholeUnit.plural} would be required. Choose a whole-tablet volume (${recipe.wholeUnit.volumePerUnit} mL steps).`;}
 text('sachet-note',unitNote);$('sachet-note').hidden=!unitNote;text('version',`Recipe ${recipe.version} · pack ${pack.version} · sources checked ${pack.reviewed}`);$('sources').replaceChildren();for(const source of recipe.sources){const li=node('li'),a=node('a',source.title);a.href=source.url;a.target='_blank';a.rel='noopener noreferrer';li.append(a);$('sources').append(li);}text('changes',Array.isArray(pack.changelog)?pack.changelog.filter(x=>typeof x==='string').join(' '):'');text('local-history',recipe.local?`Saved on this device · revision ${recipe.version} · ${recipe.savedAt}. ${recipe.history?.length||0} previous revision(s) retained.`:recipe.shared?'Opened from this URL; not saved to this device.':'Custom recipes remain on this device unless you export or share them.');
 renderPrint(active,values,rows,osm);syncUrl();
}
function setVolume(value){if(!validVolume(value)){$('volume-error').hidden=false;$('volume').setAttribute('aria-invalid','true');return false;}$('volume-error').hidden=true;$('volume').removeAttribute('aria-invalid');volume=value;render();return true;}
$('volume').addEventListener('input',()=>{const value=$('volume').valueAsNumber;if(!setVolume(value))text('volume-error','Enter 50–5,000 mL. Results retain the last valid volume.');});$('slider').addEventListener('input',e=>setVolume(Number(e.target.value)));$('minus').onclick=()=>setVolume(Math.max(50,volume-50));$('plus').onclick=()=>setVolume(Math.min(5000,volume+50));for(const b of document.querySelectorAll('[data-volume]'))b.onclick=()=>setVolume(Number(b.dataset.volume));for(const [id,value]of [['weight','weight'],['spoons','spoons']])$(id).onclick=()=>{mode=value;render();};$('salt-choice').onchange=()=>{saltChoice=$('salt-choice').value;render();};$('base-choice').onchange=()=>{baseChoice=$('base-choice').value;render();};$('glucose-choice').onchange=()=>{glucoseChoice=$('glucose-choice').value;render();};$('recipe').onchange=()=>{recipe=allRecipes().find(r=>r.id===$('recipe').value);resetSubstitutions();$('editor').hidden=true;render();};
function renderEditor(){$('editor-rows').replaceChildren();draft.forEach((row,index)=>{const div=node('div',undefined,'editor-row'),line=node('div',undefined,'editor-line'),label=node('label',`${INGREDIENTS[row.id].name} (${INGREDIENTS[row.id].unit}/L)`);label.htmlFor=`amount-${index}`;const input=node('input');input.id=`amount-${index}`;input.type='number';input.min='0';input.max='1000';input.step='any';input.required=true;input.value=row.amount;input.oninput=()=>row.amount=input.valueAsNumber;const remove=node('button','×');remove.type='button';remove.setAttribute('aria-label',`Remove ${INGREDIENTS[row.id].name}`);remove.onclick=()=>{draft.splice(index,1);renderEditor();};line.append(label,input,remove);div.append(line);if(row.id==='losalt'){const ratios=node('div',undefined,'salt-ratios');for(const [key,labelText]of [['naclPercent','NaCl %'],['kclPercent','KCl %']]){const ratioLabel=node('label',labelText),field=node('input');field.type='number';field.min='0';field.max='100';field.step='any';field.required=true;field.value=row[key]??'';field.oninput=()=>row[key]=field.valueAsNumber;ratioLabel.append(field);ratios.append(ratioLabel);}div.append(ratios);}div.append(node('p',INGREDIENTS[row.id].note||'Check identity and purity.','small muted'));$('editor-rows').append(div);});$('add-ingredient').replaceChildren();for(const [id,def]of Object.entries(INGREDIENTS)){if(draft.some(r=>r.id===id)||id.startsWith('product')||['reliefCitrate','pedialyte','clinova'].includes(id))continue;const option=node('option',def.name);option.value=id;$('add-ingredient').append(option);}$('add-row').disabled=!$('add-ingredient').options.length;}
function customName(value){const suffix=' - custom recipe',name=value.trim();return name.toLowerCase().endsWith(suffix)?name:name.slice(0,100-suffix.length)+suffix;}
$('start-editor').onclick=()=>{editingId=recipe.local?recipe.id:null;draft=structuredClone(activeRecipe().ingredients);$('custom-name').value=customName(recipe.name);$('editor').hidden=false;$('editor-error').hidden=true;renderEditor();};$('cancel-editor').onclick=()=>{$('editor').hidden=true;};$('add-row').onclick=()=>{const id=$('add-ingredient').value;if(id){draft.push({id,amount:0});renderEditor();}};$('editor').onsubmit=e=>{e.preventDefault();try{if(!draft.length||draft.every(r=>!r.amount))throw Error('Enter at least one non-zero ingredient.');if(draft.some(r=>r.id.startsWith('product')||['reliefCitrate','pedialyte','clinova'].includes(r.id)))throw Error('Replace product-specification ingredients with confirmed chemical forms before saving.');const previous=local.find(r=>r.id===editingId),r={id:editingId||`local-${crypto.randomUUID()}`,name:customName($('custom-name').value),version:String(Number(previous?.version||0)+1),local:true,savedAt:new Date().toISOString().slice(0,10),category:'Custom recipe',group:'Custom recipes · this device',carbohydrateForm:'Entered ingredients',volumeBasis:'final',compositionMode:'calculated',ingredients:structuredClone(draft),sources:structuredClone(recipe.sources),history:previous?[...(previous.history||[]),{version:previous.version,ingredients:previous.ingredients,savedAt:previous.savedAt}].slice(-20):[]};validateRecipe(r);const next=[...local.filter(x=>x.id!==r.id),r];if(!save(LOCAL_KEY,next))throw Error('Could not save to this device.');local=next;$('editor').hidden=true;populateRecipes(r.id);}catch(error){text('editor-error',error.message);$('editor-error').hidden=false;}};
$('export').onclick=()=>{const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),appVersion:APP_VERSION,packVersion:pack.version,volumeML:volume,recipe:activeRecipe()},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=node('a');a.href=url;a.download=`${recipe.id}-${volume}ml-v${recipe.version}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
async function copyText(value){try{await navigator.clipboard.writeText(value);return true;}catch{const field=node('textarea');field.value=value;field.setAttribute('readonly','');field.style.position='fixed';field.style.opacity='0';document.body.append(field);field.select();const ok=document.execCommand?.('copy');field.remove();return !!ok;}}
$('share').onclick=async()=>{syncUrl();const url=location.href,title=`${recipe.name} · ${format(volume)} mL`;try{if(navigator.share){await navigator.share({title,text:title,url});text('share-status','Share sheet opened.');}else{text('share-status',await copyText(url)?'Recipe link copied.':'Copy the URL from the address bar.');}}catch(error){if(error.name!=='AbortError')text('share-status',await copyText(url)?'Recipe link copied.':'Copy the URL from the address bar.');}};
$('print').onclick=()=>{render();window.print();};window.addEventListener('beforeprint',()=>{if(recipe)render();});
function showUpdate(){const shell=registration?.waiting,parts=[];if(pendingPack)parts.push(`Recipe pack ${pendingPack.version} available.`);if(shell)parts.push('App update available.');text('update-text',parts.join(' '));$('update-banner').hidden=!parts.length;}
async function checkUpdates(manual=false){if(manual){$('check-updates').disabled=true;text('check-result','Checking…');}try{const next=await fetchPack();networkState='Online · recipes checked';if(compareVersions(next.version,pack.version)>0){pendingPack=next;showUpdate();text('check-result',`Pack ${next.version} is ready to apply.`);}else if(compareVersions(next.version,pack.version)===0&&JSON.stringify(next)!==JSON.stringify(pack))text('check-result','The server changed a recipe without a version bump. Keeping the saved pack.');else text('check-result',compareVersions(next.version,pack.version)<0?'Server pack is older; keeping the newer saved pack.':'You have the latest available recipe pack.');}catch{networkState='Offline / unreachable · saved recipes';text('check-result','Could not check for updates. Your saved recipes remain available.');}finally{updateStatus();$('check-updates').disabled=false;}if(manual&&registration)registration.update().catch(()=>{});}
$('check-updates').onclick=()=>checkUpdates(true);$('apply-update').onclick=async()=>{if(pendingPack){const selected=recipe.id;pack=pendingPack;pendingPack=null;save(PACK_KEY,pack);await cachePack(pack);populateRecipes(selected);}if(registration?.waiting){registration.waiting.postMessage({type:'SKIP_WAITING'});navigator.serviceWorker.addEventListener('controllerchange',()=>location.reload(),{once:true});}showUpdate();};async function cachePack(data){try{const cache=await caches.open('ors-validated-recipes');await cache.put(new URL('./data/recipes-v2.json',location.href),new Response(JSON.stringify(data),{headers:{'Content-Type':'application/json'}}));}catch{}}
window.addEventListener('online',()=>{if(pack)checkUpdates();});window.addEventListener('offline',updateStatus);
const standalone=matchMedia('(display-mode: standalone)');let installDismissed=read(INSTALL_KEY)===true;function updateInstallBar(){$('install-bar').hidden=standalone.matches||navigator.standalone===true||installDismissed;}updateInstallBar();standalone.addEventListener('change',updateInstallBar);window.addEventListener('appinstalled',()=>{installPrompt=null;$('install-bar').hidden=true;});window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;updateInstallBar();});$('dismiss-install').onclick=()=>{installDismissed=true;save(INSTALL_KEY,true);updateInstallBar();};$('install').onclick=async()=>{if(installPrompt){const prompt=installPrompt;installPrompt=null;try{await prompt.prompt();const choice=await prompt.userChoice;if(choice.outcome==='accepted'){$('install-bar').hidden=true;return;}}catch{}}const ua=navigator.userAgent,ios=/iPad|iPhone|iPod/.test(ua)||(/Macintosh/.test(ua)&&navigator.maxTouchPoints>1),mac=/Macintosh/.test(ua);text('install-help',ios?'In Safari: Share → Add to Home Screen → Add.':mac?'In Safari: File → Add to Dock. In Chrome: menu → Cast, save and share → Install page as app.':'In Chrome: menu → Install app or Add to Home screen.');$('install-help').hidden=false;};
async function setupOffline(){if(!('serviceWorker'in navigator)){text('offline-ready','Offline storage unsupported');return;}try{registration=await navigator.serviceWorker.register('./sw.js',{scope:'./',updateViaCache:'none'});if(registration.waiting)showUpdate();registration.addEventListener('updatefound',()=>{const worker=registration.installing;worker?.addEventListener('statechange',()=>{if(worker.state==='installed'&&navigator.serviceWorker.controller)showUpdate();});});await navigator.serviceWorker.ready;const ready=await new Promise(resolve=>{const channel=new MessageChannel(),timer=setTimeout(()=>resolve(false),5000);channel.port1.onmessage=e=>{clearTimeout(timer);resolve(e.data.ready);};registration.active.postMessage({type:'CHECK_READY'},[channel.port2]);});text('offline-ready',ready?'Offline ready':'Offline save incomplete');text('storage-status',ready?'App and recipe pack are saved locally.':'Offline setup has not confirmed a complete copy.');}catch{text('offline-ready','Offline save failed');text('storage-status','Offline setup needs HTTPS or localhost and available browser storage.');}}
async function boot(){const cached=getCachedPack();try{const fresh=await fetchPack();pack=cached&&compareVersions(cached.version,fresh.version)>0?cached:fresh;if(cached&&compareVersions(fresh.version,cached.version)===0&&JSON.stringify(cached)!==JSON.stringify(fresh))pack=cached;networkState='Online · recipes checked';}catch(error){pack=cached||error.fallback;networkState='Offline / unreachable · saved recipes';}if(!pack){text('fatal','No valid recipe pack is available. Connect to the internet and reload.');$('fatal').hidden=false;updateStatus();return;}save(PACK_KEY,pack);await cachePack(pack);const stored=read(LOCAL_KEY);if(Array.isArray(stored))for(const r of stored){try{validateRecipe(r);if(r.local&&r.id.startsWith('local-')&&!local.some(x=>x.id===r.id))local.push(r);}catch{}}booted=true;if(!applySharedState(readSharedState()))populateRecipes();$('workspace').hidden=false;text('app-version',`ORS Recipes · app ${APP_VERSION}`);updateStatus();setupOffline();}
boot();
